title: Adam Galvan(or website title)
logo: "/images/AvatarMaker.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  this portfolio is created for my web design class
  <br><br>
  If you ever need any help with making a good website  
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

